---
# Creating Interface Builder configurations

- name: Create common configs for spines and leafs
  hosts: leafs_DC1, leafs_DC2, spines_DC1, spines_DC2
  tasks: 
    - name: Register variables (underlay)
      include_vars:
        file: "{{ lookup('env', 'PWD') }}/vars/underlay.yml"
        name: underlay

    - name: Ensure config directory exists
      file:
        path: "{{ lookup('env', 'PWD') }}/configs/{{ inventory_hostname }}"
        state: directory

    - name: Create Interface config
      template:
        src: "{{ lookup('env', 'PWD') }}/templates/interfaces.j2"
        dest: "{{ lookup('env', 'PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_interface.cfg"

    - name: Upload config
      eos_config:
        src: "{{ lookup('env', 'PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_interface.cfg"

