---
# Creating Underlay BGP configuration for Leafs

- name: Create leaf configurations for BGP underlay 
  hosts: leaf1-DC1, leaf2-DC1,leaf3-DC1,leaf4-DC1,leaf1-DC2, leaf2-DC2,leaf3-DC2,leaf4-DC2
  tasks: 
    - name: Register variables (underlay)
      include_vars:
        file: "{{ lookup('env', 'PWD') }}/vars/underlay.yml"
        name: underlay

    - name: Configure BGP Underlay
      template:
        src: "{{ lookup('env', 'PWD') }}/templates/bgp_Undelay_Leaf.j2"
        dest: "{{ lookup('env', 'PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_bgp_Undelay_Leaf.cfg"

    - name: Upload config
      eos_config:
        src: "{{ lookup('env', 'PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_bgp_Undelay_Leaf.cfg"

