---
# Creating VXLAN configuration for Leafs12 in DC1

- name: Create leaf configurations for underlay and VXLAN tenants
  hosts: leaf1-DC1, leaf2-DC1,leaf1-DC2, leaf2-DC2
  tasks: 
    - name: Register variables (underlay)
      include_vars:
        file: "{{ lookup('env', 'PWD') }}/vars/underlay.yml"
        name: underlay

    - name: Register VXLAN variables
      include_vars:
        file: "{{ lookup('env', 'PWD') }}/vars/Leaf12_VXLAN.yml"
        name: VXLAN

    - name: Create VXLAN Configuration
      template: 
        src: "{{ lookup('env', 'PWD') }}/templates/Leaf_VXLAN.j2"
        dest: "{{ lookup('env', 'PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_Leaf12_VXLAN.cfg"

    - name: Upload config
      eos_config:
        src: "{{ lookup('env', 'PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_Leaf12_VXLAN.cfg"
